version = 1

test_patterns = [
  "\"**/*.test.js\",",
  "\"**/*.spec.js\",",
  "\"**/tests/**/*.js\",",
  "\"**/__tests__/**/*.js\""
]

exclude_patterns = [
  "\"node_modules\",",
  "\"**/node_modules/**\",",
  "\"*.min.js\",",
  "\"*.bundle.js\",",
  "\"client/dist\",",
  "\"client/build\""
]

[[analyzers]]
name = "docker"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]